name: Pull ML dockerhub 

on:
  push:
    branches: [ "master" ]
    
env:
        DCREPOSITORY: shahlo/recomendation-anime
        IMAGE_TAG: '${{ github.sha }}'      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      


    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to DockerHub
      run: |
        docker build -t $DCREPOSITORY:$IMAGE_TAG .
        docker push $DCREPOSITORY:$IMAGE_TAG
